service: abandon-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-dotenv-plugin

functions:
  api:
    handler: src/app.handler
    events:
      - httpApi: '*'
